# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x02pb\",\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2;\n\rSearchService\x12*\n\rProcessSearch\x12\x0b.pb.Request\x1a\x0c.pb.ResponseB\x07Z\x05../pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005../pb'
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=64
  _globals['_RESPONSE']._serialized_start=66
  _globals['_RESPONSE']._serialized_end=92
  _globals['_SEARCHSERVICE']._serialized_start=94
  _globals['_SEARCHSERVICE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
